dz_geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit')
]

dz_geekshop/basketapp/urls.py
from django.urls import path

from .views import add, remove

app_name = 'basketapp'

urlpatterns = [
    path('add/<int:product_pk>/', add, name='add'),
    path('remove/<int:product_pk/', remove, name='remove'),
]

dz_geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from mainapp import views as mainapp
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', mainapp.products, name='products'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contacts/', mainapp.contacts, name='contacts'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dz_geekshop/mainapp/urls.py
from django.urls import path

from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
]

dz_geekshop/authapp/models.py
from django.db import models
from django.contrib.auth.models import  AbstractUser

class ShopUser(AbstractUser):
    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    avatar = models.ImageField(upload_to='users_avatar', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

    def __str__(self):
        return self.username

dz_geekshop/basketapp/models.py
from django.db import models
from authapp.models import ShopUser
from mainapp.models import Product


class BasketSlot(models.Model):
    class Meta:
        verbose_name = 'Слот корзины'
        verbose_name_plural = 'Слоты корзины'
    user = models.ForeignKey(ShopUser, verbose_name='пользователь', on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, verbose_name='продукт', on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(verbose_name='количество', default=1)
    created = models.DateTimeField(verbose_name='дата и время создания', auto_now_add=True)

    def __str__(self):
        return '{} - {}'.format(self.user.username, self.product.name)

dz_geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
    name = models.CharField(verbose_name='имя категории', max_length=256, unique=True)
    description = models.TextField(verbose_name='описание категории', max_length=1000, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
    category = models.ForeignKey(ProductCategory, verbose_name='категория', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=64)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name="подробное описание продукта", blank=True)
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    image = models.ImageField(verbose_name='изображение', upload_to='product_images')
    quantity = models.PositiveSmallIntegerField(verbose_name='склад', default=0)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

dz_geekshop/authapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import ShopUser
from django import forms


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


def clean_age(self):
    data = self.cleaned_data['age']
    if data < 18:
        raise forms.ValidationError("Вы слишком молоды!")

    return data

dz_geekshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.views.generic.edit import UpdateView
from django.contrib import auth
from .forms import ShopUserRegisterForm

def login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(request, username=username, password=password)
        if user:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))

    return render(request, 'authapp/login.html')


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main'))


def register(request):
    form = ShopUserRegisterForm()
    if request.method == "POST":
        form = ShopUserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main'))
    context = {'form': form}
    return render(request, 'authapp/register.html', context)


class EditView(UpdateView):
    pass

dz_geekshop/basketapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import BasketSlot
from mainapp.models import Product


def add(request, product_pk):
    product = get_object_or_404(Product, pk=product_pk)
    if request.user.is_authenticated:
        basket_slot = request.user.basket.filter(product=product).first()
        if basket_slot:
            basket_slot.quantity += 1
            basket_slot.save()
        else:
            new_basket_slot = BasketSlot(user=request.user, product=product)
            new_basket_slot.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def remove(request, product_pk=None):
    product = get_object_or_404(Product, pk=product_pk)
    basket_slot = BasketSlot.objects.filter(user=request.user, product=product).first()

    if basket_slot:
        if basket_slot.quantity == 1:
            basket_slot.delete()
        else:
            basket_slot.quantity -= 1
            basket_slot.save()

    return HttpResponseRedirect(request.META('HTTP_REFERER'))

dz_geekshop/mainapp/views.py
from django.shortcuts import render
from .models import Product, ProductCategory

def main(request):
    return render(request, 'mainapp/main.html')


def contacts(request):
    return render(request, 'mainapp/contacts.html')


def products(request, pk=None):
    product_list = Product.objects.all()
    if pk:
        product_list = product_list.filter(category__pk=pk)
    context = {'products': product_list, 'categories': ProductCategory.objects.all, 'basket':request.user.basket.all()}
    return render(request, 'mainapp/products.html', context)

dz_geekshop/authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% block content %}
    <form class = "form-horizontal" method="POST">
        {% csrf_token %}
        <input name="username" type="text", placeholder="Введите ваш логин">
        <input name="password"type="password", placeholder="Введите ваш пароль">
        <input type="submit", value="Войти">
    </form>
{% endblock %}

dz_geekshop/authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
{% block content %}
    <form enctype='multipart/form-data' method="POST" class = "form-horizontal">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Зарегистрироваться">
    </form>
{% endblock %}

dz_geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    {% block title%}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/boostrap.min.css' %}">

</head>
<body>
{% include 'mainapp/includes/inc_menu.html' %}
{% block content %}
{% endblock %}
{% block js %}
{% endblock %}
</body>
</html>

dz_geekshop/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html'%}
{% block title %}
    <title>Контакты</title>
{% endblock %}

{% block content%}
    <h1>Контакты</h1>

{% endblock %}

dz_geekshop/mainapp/templates/mainapp/includes/inc_menu.html
<ul class = "links-menu" style="background-color: #d5d5d5; padding-bottom: 5px">
    <a href="{% url 'main' %}">Главная</a>
    <a href="{% url 'contacts' %}">Контакты</a>
    <a href="{% url 'products' %}">Продукты</a>
</ul>

dz_geekshop/mainapp/templates/mainapp/main.html
{% extends 'mainapp/base.html'%}
{% block title %}
    <title>Главная</title>
{% endblock %}

{% block content%}
    <h1 class>Главная</h1>
    {% if request.user.is_authenticated %}
        <div class = "divtext">Добро пожаловать, {{request.user.username | title}}</div>
        <a href="{% url 'auth:logout'%}">Выйти</a>
    {% else %}
        <div class = "divtext">Добро пожаловать <br>
        <a href="{% url 'auth:login'%}">Войти</a>
        <a href="{% url 'auth:register'%}">Зарегистрироваться</a>
        </div>
    {% endif %}
{% endblock %}

dz_geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html'%}
{% block title %}
    <title>Продукты</title>
{% endblock %}

{% block content%}
    <h1>Продукты</h1>
    {% include 'mainapp/includes/inc_category.html' %}
    {% for product in products%}
        <div class ="form-control" style="width:20%">
            <div>Количество продуктов в корзине: {{ basket|length }}</div>
            <div class = divtext>{{product.name}}</div>
            <img style= "width:50%"src="http://127.0.0.1:8000/media/{{product.image}}" alt="Изображение продукта">
            <p style="text-align:left; font-size: 13px">{{product.short_desc}}</p>
            <a href="{% url 'basket:add' product.pk %}" style="font-size: 12px">Добавить в корзину</a>
            <br>
            <a href="{% url 'basket:remove' product.pk %}" style="font-size: 12px">Удалить из корзины</a>
            <div style="text-align:right; font-size: 15px">{{product.price}}₽</div>
        </div>
    {% endfor %}
{% endblock %}